# Path to your oh-my-zsh installation.
#export ZSH=/home/sander/.oh-my-zsh
export ZSH=/usr/share/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="mortalscumbag"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git python vagrant z)

# User configuration

export PATH="/sw/bin:/sw/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:~/.config/composer/vendor/bin"
export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vi'
else
  export EDITOR='nano'
fi

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#export JAVA_HOME=$(/usr/libexec/java_home)

#export ANDROID_HOME=/home/sander/Android/Sdk
export ANDROID_HOME=/opt/android-sdk


export PATH=/usr/local/bin/go/bin:$PATH
export PATH="/usr/local/opt/qt/bin:$PATH:${JAVA_HOME}/bin"
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_HOME/build-tools/33.0.0:$PATH
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
#export PATH="~/.config/composer/vendor/bin:$PATH"
export PATH="~/.gem/ruby/2.5.0/bin:$PATH"
export PATH="~/.config/composer/vendor/bin:$PATH"

alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'

alias homestead_up='cd ~/VMs/homestead && vagrant up'
alias homestead_down='cd ~/VMs/homestead && vagrant halt'
alias homestead_ssh='cd ~/VMs/homestead && vagrant ssh'
alias homestead_status='cd ~/VMs/homestead && vagrant status'

alias ha_mount='sshfs -o allow_other,IdentityFile=~/.ssh/id_rsa root@hawking:/storage/configuration/homeassistant-config /home/sander/ha'

alias hawking_mount_storage='sshfs -o allow_other,IdentityFile=~/.ssh/id_rsa root@10.0.0.3:/storage /home/sander/hawking/storage'
alias hawking_services_mount='sshfs -o allow_other,IdentityFile=~/.ssh/id_rsa root@10.0.0.3:/storage/services /home/sander/hawking/services'
alias hawking_downloads_mount='sshfs -o allow_other,IdentityFile=~/.ssh/id_rsa root@10.0.0.3:/storage/downloads /home/sander/hawking/downloads'
alias hawking_media_mount='sshfs -o allow_other,IdentityFile=~/.ssh/id_rsa root@10.0.0.3:/storage/media /home/sander/hawking/media'
alias hawking_config_mount='sshfs -o allow_other,IdentityFile=~/.ssh/id_rsa root@10.0.0.3:/storage/configuration /home/sander/hawking/configuration'

alias vps_services_mount='sshfs -o allow_other,IdentityFile=~/.ssh/id_rsa root@163.172.164.110:/srv/docker-compose /home/sander/vps/services'
alias vps_config_mount='sshfs -o allow_other,IdentityFile=~/.ssh/id_rsa root@163.172.164.110:/etc /home/sander/vps/etc'

alias weather="curl v2.wttr.in/Utrecht"

export CAPACITOR_ANDROID_STUDIO_PATH=/opt/android-studio/bin/studio.sh
#export LIBVA_DRIVER_NAME=radeonsi
export MOZ_ENABLE_WAYLAND=1

eval "$(rbenv init - zsh)"

#export open='nautilus $1'

xset b off
xset b 0 0 0

unsetopt BEEP
source /usr/share/nvm/init-nvm.sh
#. ~/tools/z/z.sh

alias reset_term='~/tools/after-ssh.sh'

#if [[ ! -o login ]]; then
  # don't do this in a login shell
  # because it happens anyway
  #. ~/.zlogout
  #~/tools/after-ssh.sh
  #echo "LOGGING OUT!"
#fi
\
